# Generated by Django 4.2.6 on 2024-03-15 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory_fr',
            name='categoryThrough',
        ),
        migrations.RemoveField(
            model_name='postcategory_fr',
            name='postThrough',
        ),
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='categoryThrough',
        ),
        migrations.RemoveField(
            model_name='postcategory_ru',
            name='postThrough',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory_fr',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postCategory_ru',
        ),
        migrations.DeleteModel(
            name='PostCategory_en',
        ),
        migrations.DeleteModel(
            name='PostCategory_fr',
        ),
        migrations.DeleteModel(
            name='PostCategory_ru',
        ),
    ]
